# Generated by Django 5.0.4 on 2024-05-04 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postfavorite_post_favorites'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='datetiem_created',
            new_name='datetime_created',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['datetime_created'], name='notificatio_datetim_2dc8ca_idx'),
        ),
    ]
