# Generated by Django 5.0.4 on 2024-05-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postfavorite_post_favorites'),
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notify_comment', to='blog.comment'),
            preserve_default=False,
        ),
    ]
